# Create a new user
POST http://localhost:3001/user/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user2@notfound.ru",
  "name": "Keks",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3001/user/auth/684648cc7ca4860099c416fd HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODQzYzU3NTI2YjkyMTU1YzMzNTIwOTIiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQucnUiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTc1MDA1NzQ3MiwiZXhwIjoxNzUwMDU3NzcyfQ.VtEfToEcDEPOOslJp1v0jHsJKwdvVdOu4qjSGGaQUMM
###
# Demo route for Pipe
GET http://localhost:3001/user/auth/refresh HTTP/1.1
 Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODQzYzU3NTI2YjkyMTU1YzMzNTIwOTIiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQucnUiLCJuYW1lIjoiS2VrcyIsImlhdCI6MTc1MDA1NzgwNiwiZXhwIjoxNzUwMDU4MTA2fQ.uecIxjda-mxow4NOb3ZztyvJysvb2qlqnr2VdIojjLE
###

# Login user by email and password
POST http://localhost:3001/user/auth/login HTTP/1.1
Content-Type: application/json

{
  "id": "684648cc7ca4860099c416fd",
  "email": "user@notfound.ru",
  "password": "123456"
}

###
